/*
 * FreeRTOS Kernel V10.2.0
 * Copyright (C) 2019 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://www.FreeRTOS.org
 * http://aws.amazon.com/freertos
 *
 * 1 tab == 4 spaces!
 */

/* 
	NOTE : Tasks run in system mode and the scheduler runs in Supervisor mode.
	The processor MUST be in supervisor mode when vTaskStartScheduler is 
	called.  The demo applications included in the FreeRTOS.org download switch
	to supervisor mode prior to main being called.  If you are not using one of
	these demo application projects then ensure Supervisor mode is used.
*/
  

/*
 * Creates all the demo application tasks, then starts the scheduler.  The WEB
 * documentation provides more details of the demo application tasks.
 * 
 * Main.c also creates a task called "Check".  This only executes every three 
 * seconds but has the highest priority so is guaranteed to get processor time.  
 * Its main function is to check that all the other tasks are still operational.
 * Each task (other than the "flash" tasks) maintains a unique count that is 
 * incremented each time the task successfully completes its function.  Should 
 * any error occur within such a task the count is permanently halted.  The 
 * check task inspects the count of each task to ensure it has changed since
 * the last time the check task executed.  If all the count variables have 
 * changed all the tasks are still executing error free, and the check task
 * toggles the onboard LED.  Should any task contain an error at any time 
 * the LED toggle rate will change from 3 seconds to 500ms.
 *
 */

/* Standard includes. */
#include <stdlib.h>
#include <stdio.h>

/* Scheduler includes. */
#include "FreeRTOS.h"
#include "task.h"
#include "lpc21xx.h"

/* Peripheral includes. */
#include "serial.h"
#include "GPIO.h"


/*-----------------------------------------------------------*/

/* Constants to setup I/O and processor. */
#define mainBUS_CLK_FULL	( ( unsigned char ) 0x01 )

/* Constants for the ComTest demo application tasks. */
#define mainCOM_TEST_BAUD_RATE	( ( unsigned long ) 115200 )

/*GLOBAL VARS*/
/***********************/
//TaskHandle_t Led_task_handeler = NULL;
//TaskHandle_t Button_task_handeler = NULL;

pinState_t G_button_state=0;
int number_misses=0;/*this variable will be incermented each time there will be an */
char run_time_buffer[190];/*this buffer will hold the run time statistics generated by the free RTOS*/
char test_case[190]={" H L H L Periodic trial"};
/************************/
/*
 * Configure the processor for use with the Keil demo board.  This is very
 * minimal as most of the setup is managed by the settings in the project
 * file.
 */
static void prvSetupHardware( void );
/*-----------------------------------------------------------*/

/*Implement the tick hook to be used for the seek of tesing of the tick arrival*/
void vApplicationTickHook (void)
{
	/*put your testing code here to run after each timer tick to test the tick arival on a logic analizer*/
					GPIO_write(PORT_0,PIN0,PIN_IS_HIGH);
					GPIO_write(PORT_0,PIN0,PIN_IS_LOW);
}
/*Implement the Idel hook to be used for the seek of tesing of the IDLE task arrival*/
void vApplicationIdleHook (void)
{
	/*put your testing code here to run during the occurance of the idel task in order to test it's occerance*/
					//GPIO_write(PORT_0,PIN3,PIN_IS_HIGH);
					

	//GPIO_write(PORT_0,PIN3,PIN_IS_LOW);
}
/*
 * Application entry point:
 * Starts all the other tasks, then starts the scheduler. 
 */
void Button_2_Monitor( void * pvParameters )
	{
int xLastWakeTime = xTaskGetTickCount();    /*the var used for the taskdelay until()*/
		int start_time=0,end_time=0;
		
		
		vTaskSetApplicationTaskTag(NULL,(void *)2 );
    for( ;; )
    {
			int i=0;
			for(i=0;i<100;i++)
			{
				i=i;
			}
        /* Task code goes here. */


			end_time=xTaskGetTickCount();/*before calling the delay task (finishing the task) this var will capture the task end time*/
			/*we will assume here that the task dead line is it's periodacity*/
//			if((end_time-start_time)>100)
//			{
//				/*count this event as missing the deadline of  this task*/
//				number_misses++;
//			}

      vTaskDelayUntil( &xLastWakeTime, 50 );
		

			
    }
	}
	
	void Button_1_Monitor( void * pvParameters )
	{
		int xLastWakeTime = xTaskGetTickCount();    /*the var used for the taskdelay until()*/
		vTaskSetApplicationTaskTag(NULL,(void *)1 );

		
 
    for( ;; )
    {
			int i=0;
	
        /* Task code goes here. */
			for(i=0;i<100;i++)
			{
				i=i;
			}

			

			vTaskDelayUntil( &xLastWakeTime, 50 );


			
    }
	}
	
		void Periodic_Transmitter( void * pvParameters )
	{
		int xLastWakeTime = xTaskGetTickCount();    /*the var used for the taskdelay until()*/
		vTaskSetApplicationTaskTag(NULL,(void *)3);

		
 
    for( ;; )
    {
			int i=0;
	
        /* Task code goes here. */
			for(i=0;i<100;i++)
			{
				i=i;
			}


			

			vTaskDelayUntil( &xLastWakeTime, 100 );


			
    }
	}
	
	
			void Uart_Receiver( void * pvParameters )
	{
		int xLastWakeTime = xTaskGetTickCount();    /*the var used for the taskdelay until()*/
		int i=0;
		vTaskSetApplicationTaskTag(NULL,(void *)4 );

		
 
    for( ;; )
    {
	
        /* Task code goes here. */
			
	
        /* Task code goes here. */
			for(i=0;i<100;i++)
			{
				i=i;
			}


			

			vSerialPutString(test_case,50);
			vTaskDelayUntil( &xLastWakeTime, 20 );

			
			xSerialPutChar('\n');

			
    }
	}
	
	
	
			void Load_1_Simulation( void * pvParameters )
	{
		int xLastWakeTime = xTaskGetTickCount();    /*the var used for the taskdelay until()*/
		vTaskSetApplicationTaskTag(NULL,(void *)5 );

		

    for( ;; )
    {
	 unsigned long int i=0;
        /* Task code goes here. */
			for(i=0;i<33000;i++)
			{
				i=i;
			}


			

			vTaskDelayUntil( &xLastWakeTime, 10 );


			
    }
	}
	
	
			void Load_2_Simulation( void * pvParameters )
	{
		int xLastWakeTime = xTaskGetTickCount();    /*the var used for the taskdelay until()*/
		vTaskSetApplicationTaskTag(NULL,(void *)6 );

		

		
    for( ;; )
    {
	 unsigned long int i=0;
        /* Task code goes here. */
			for(i=0;i<79000;i++)
			{
				i=i;
			}

 
			
			//GPIO_write(PORT_0,PIN3,PIN_IS_HIGH);
			//GPIO_write(PORT_0,PIN6,PIN_IS_LOW);/*this is the last line before the delay so it is the end of the task*/
			vTaskDelayUntil( &xLastWakeTime, 100 );
			//GPIO_write(PORT_0,PIN6,PIN_IS_HIGH);/*this is the first line of the task after the vdelaytask so it is the begining of the task*/
			//GPIO_write(PORT_0,PIN3,PIN_IS_LOW);
			//vTaskGetRunTimeStats(run_time_buffer);
			//vSerialPutString(run_time_buffer,190);
			//xSerialPutChar('\n');

			
    }
	}
int main( void )
{
	/* Setup the hardware for use with the Keil demo board. */
  //prvSetupHardware();
	GPIO_init();
	xSerialPortInitMinimal(mainCOM_TEST_BAUD_RATE);
	
	

 
/*********************************Creating the Normal tasks used in the FP scheduler***************************************************************************************/	
    /* Create Tasks here */
	/*Creating the LED task*/
//	xTaskCreate(
//                    Led_task,       /* Function that implements the task. */
//                    "LED_ TASK",          /* Text name for the task. */
//                    100,      /* Stack size in words, not bytes. */
//                    ( void * ) 0,    /* Parameter passed into the task. */
//                    2,/* Priority at which the task is created. */
//                    &Led_task_handeler );      /* Used to pass out the created task's handle. */

	/*Creating the Button task*/
//	xTaskCreate(
//                    Button_task,       /* Function that implements the task. */
//                    "BUTTON_ TASK",          /* Text name for the task. */
//                    100,      /* Stack size in words, not bytes. */
//                    ( void * ) 0,    /* Parameter passed into the task. */
//                    1,/* Priority at which the task is created. */
//                    &Button_task_handeler );      /* Used to pass out the created task's handle. */



/*********************************Creating the periodic tasks used in the EDF scheduler***************************************************************************************/

	/*Creating the Button task*/
	xTaskPeriodicCreate(
                    Button_1_Monitor,       /* Function that implements the task. */
                    "BUTTON_1_Monitor",          /* Text name for the task. */
                    100,      /* Stack size in words, not bytes. */
                    ( void * ) 0,    /* Parameter passed into the task. */
                    0,/* Priority at which the task is created. */
                    NULL,/* Used to pass out the created task's handle. */
										50 /*this is the task period*/);      

	xTaskPeriodicCreate(
                    Button_2_Monitor,       /* Function that implements the task. */
                    "BUTTON_2_Monitor",          /* Text name for the task. */
                    100,      /* Stack size in words, not bytes. */
                    ( void * ) 0,    /* Parameter passed into the task. */
                    0,/* Priority at which the task is created. */
                    NULL,/* Used to pass out the created task's handle. */
										50 /*this is the task period*/);
										
	xTaskPeriodicCreate(
                    Periodic_Transmitter,       /* Function that implements the task. */
                    "Periodic_Transmitter",          /* Text name for the task. */
                    100,      /* Stack size in words, not bytes. */
                    ( void * ) 0,    /* Parameter passed into the task. */
                    0,/* Priority at which the task is created. */
                    NULL,/* Used to pass out the created task's handle. */
										100 /*this is the task period*/);		


	xTaskPeriodicCreate(
                    Uart_Receiver,       /* Function that implements the task. */
                    "Uart_Receiver",          /* Text name for the task. */
                    100,      /* Stack size in words, not bytes. */
                    ( void * ) 0,    /* Parameter passed into the task. */
                    0,/* Priority at which the task is created. */
                    NULL,/* Used to pass out the created task's handle. */
										20 /*this is the task period*/);											
										

	xTaskPeriodicCreate(
                    Load_1_Simulation,       /* Function that implements the task. */
                    "Load_1_Simulation",          /* Text name for the task. */
                    100,      /* Stack size in words, not bytes. */
                    ( void * ) 0,    /* Parameter passed into the task. */
                    0,/* Priority at which the task is created. */
                    NULL,/* Used to pass out the created task's handle. */
										10 /*this is the task period*/);	


	xTaskPeriodicCreate(
                    Load_2_Simulation,       /* Function that implements the task. */
                    "Load_2_Simulation",          /* Text name for the task. */
                    100,      /* Stack size in words, not bytes. */
                    ( void * ) 0,    /* Parameter passed into the task. */
                    0,/* Priority at which the task is created. */
                    NULL,/* Used to pass out the created task's handle. */
										100 /*this is the task period*/);	



















/********************************************************************************************************************************/
	/* Now all the tasks have been started - start the scheduler.

	NOTE : Tasks run in system mode and the scheduler runs in Supervisor mode.
	The processor MUST be in supervisor mode when vTaskStartScheduler is 
	called.  The demo applications included in the FreeRTOS.org download switch
	to supervisor mode prior to main being called.  If you are not using one of
	these demo application projects then ensure Supervisor mode is used here. */
	vTaskStartScheduler();

	/* Should never reach here!  If you do then there was not enough heap
	available for the idle task to be created. */
	for( ;; );
}
/*-----------------------------------------------------------*/

/* Function to reset timer 1 */
void timer1Reset(void)
{
	T1TCR |= 0x2;
	T1TCR &= ~0x2;
}

/* Function to initialize and start timer 1 */
static void configTimer1(void)
{
	T1PR = 1000;
	T1TCR |= 0x1;
}

static void prvSetupHardware( void )
{
	/* Perform the hardware setup required.  This is minimal as most of the
	setup is managed by the settings in the project file. */

	/* Configure UART */
	xSerialPortInitMinimal(mainCOM_TEST_BAUD_RATE);

	/* Configure GPIO */
	GPIO_init();
	
	/* Config trace timer 1 and read T1TC to get current tick */
	configTimer1();

	/* Setup the peripheral bus to be the same as the PLL output. */
	VPBDIV = mainBUS_CLK_FULL;
}
/*-----------------------------------------------------------*/


